var regionData = [
  {
    region: "Albania",
    subscribersPer100: 111,
    adultLiteracyRate: 96.8,
    growthRate: -0.3,
    urbanPopulationRate: 55,
    extremePovertyRate: 0.62,
    medianAge: 32.56,
  },
  {
    region: "Algeria",
    subscribersPer100: 98,
    adultLiteracyRate: 72.6,
    growthRate: -1.9,
    urbanPopulationRate: 74,
    extremePovertyRate: 6.79,
    medianAge: 26.62,
  },
  {
    region: "Angola",
    subscribersPer100: 47,
    adultLiteracyRate: 70.4,
    growthRate: -3.1,
    urbanPopulationRate: 60,
    extremePovertyRate: 43.37,
    medianAge: 16.18,
  },
  {
    region: "Antigua and Barbuda",
    subscribersPer100: 143,
    adultLiteracyRate: 99,
    growthRate: -1.1,
    urbanPopulationRate: 30,
    extremePovertyRate: null,
    medianAge: 30.26,
  },
  {
    region: "Argentina",
    subscribersPer100: 152,
    adultLiteracyRate: 97.9,
    growthRate: -0.9,
    urbanPopulationRate: 93,
    extremePovertyRate: 0.92,
    medianAge: 30.83,
  },
];
